### ISSUE TITLE
Dependency "RxCombine" has no shared framework schemes for any of the platforms: iOS

### ISSUE THREAD

**Issue by hfabisiak** [CombineCommunity/RxCombine#10]
After `carthage update --platform iOS` I get an error: `Dependency "RxCombine" has no shared framework schemes for any of the platforms: iOS`

**Comment by freak4pc** [comment]
The last release was missing a binary. Mind trying now? 

FYI as the README mentions, we only support Carthage via prebuilt binary.

**Comment by hfabisiak** [comment]
Everything is working now, thank you!

**Comment by zalogatomek** [comment]
Hi, looks like it not working for the same reason on version 2.0.1. Any chance to address this issue?

**Comment by alexfu** [comment]
I'm getting this error too on 2.0.1. I also noticed that the 2.0 versions are missing the prebuilt framework in releases...

<img width="1161" alt="Screen Shot 2022-05-05 at 10 05 29 AM" src="https://user-images.githubusercontent.com/987398/166941728-b402ace0-c04c-423e-a9fb-8db14ee951da.png">

@freak4pc Would this just be a matter of including the prebuilt framework in the release? If so, I'd be happy to also contribute a Github workflow that can create releases based on tag pushes and run `carthage-archive.sh` to attach the prebuilt framework to the release.

**Comment by anuragajwani** [comment]
Having the same issue with 2.0.1. Any updates on when the prebuilt binary be uploaded?

**Comment by freak4pc** [comment]
Hey, seems like it. I honestly won't have the time for it anytime soon, and seems like carthage-archive.sh by itself doesn't work for me at the moment, so it's more work than just running it. 

If anyone wants to take this on, I'm happy to accept a PR. 

Regardless, these pre-built are quite the hassle to maintain because you're always locked to some specific version of Swift and it might not always fit all users of this library. I often recommend folks to fork and archive so they get exactly the right version they need.

Either way, if anyone wants to take on fixing this and making the archive, I'm happy to assist.
