### ISSUE TITLE
Unable to use in a CocoaPod

### ISSUE THREAD

**Issue by NathanielBlackburn** [CombineCommunity/RxCombine#28]
We tried to use RxCombine in a pod that we're developing. Our pod requires iOS 14.0, however, when deploying the pod via `pod repo push`, it can't pass CocoaPods validation due to RxCombine's deployment target being set to iOS 9.0:

```
    - ERROR | xcodebuild:  RxCombine/Sources/Combine+Rx/Subject+Rx.swift:19:49: error: 'Subject' is only available in iOS 13.0 or newer
    - NOTE  | xcodebuild:  RxCombine/Sources/Combine+Rx/Subject+Rx.swift:19:17: note: add @available attribute to enclosing protocol
```

Is such a low deployment target necessary? Correct me if I'm wrong, but there's no sense using RxCombine before iOS 13 anyway?

**Comment by freak4pc** [comment]
Hey Nathaniel,

The primary use case for RxCombine is using it in a project that already has RxSwift and needs bridging to Combine. Since RxSwift's minimum deployment target is iOS 9, so is this project's. Otherwise, projects with older deployment targets that want to support Combine conditionally in an older project won't be able to. 

I'm not sure why it matters though? If RxCombine is 9 and up, and you support 14 and up, there should be no conflict that I see here.

**Comment by NathanielBlackburn** [comment]
Yeah, this is more of a CocoaPods issue than anything. When CocoaPods validate podspec for `pod repo push`, it creates a dummy app and imports my pod along with all its dependencies. Since my pod requires iOS 14.0, the app itself has the same iOS version set as its minimum deployment target. But all the other dependencies' minimum deployment targets are set to what's written in their respective podspec files - thus RxCombine is set to iOS 9.0. CocoaPods then tries to build the dummy app and it fails when trying to build RxCombine with iOS 9. I understand the reasoning behind the 9.0 target, I guess we'll have to think around it ;) Thanks for your reply.
